### ISSUE TITLE
Add feature to show or hide panels and adjust size

### ISSUE THREAD

**Issue by ginocarrascomori** [wannabegeek/ng2-split-pane#10]
I like your library and it would be nice if you could add the following feature.

I want to display only one panel and hide separator if certain condition is met.

- If only one panel is detected it should have width* 100% and hide split separator.
- If two panels are detected, it should have the default width* for each one and show splitter separator.
- It should allow toggle of panels visibility at any time.

*Using vertical split

**Comment by siovene** [comment]
I would be interested in exactly the same, especially hiding one panel and the separator via an API. I'll be looking into contributing this feature in the coming weeks unless @wannabegeek wants to do it first :-)

**Comment by siovene** [comment]
Hi, just as an update, I'm working on this and I plan on submitting a PR early next week.

**Comment by siovene** [comment]
I submitted a PR for this.

**Comment by wannabegeek** [comment]
I have just released version 1.1.0 to npm with these changes.

Many thanks for the PR.

**Comment by siovene** [comment]
Wonderful, thanks for merging and for the new release!
