### ISSUE TITLE
Mehod to resize the divider

### ISSUE THREAD

**Issue by aslamkam** [wannabegeek/ng2-split-pane#34]
Say you want the divider 200px from the left so that the primary component is 200px wide. i.e. resizeDivider(200)

**Comment by darinw** [comment]
I 100% agree with this. Would have many advantages!

**Comment by darinw** [comment]
@aslamkam 

FOUND SOLUTION:
`import {HorizontalSplitPaneComponent} from "ng2-split-pane/lib/horizontal-split-pane.component";`
...
in the component you have the split pane inside:
`@ViewChild(HorizontalSplitPaneComponent) splitComponent: HorizontalSplitPaneComponent;`
`public testSizeChange(): void {
    console.log('getTotalSize', this.splitComponent.getTotalSize());
    console.log('getPrimarySize', this.splitComponent.getPrimarySize());
    console.log('getSecondarySize', this.splitComponent.getSecondarySize());

    this.splitComponent.applySizeChange(200) // px of the primary component
  }`


there is also a `this.splitComponent.dividerPosition(250)`

**Comment by aslamkam** [comment]
Thanks a lot for showing me the functions.
Since the docs didn't contain these functions, I assumed they didn't exist.
