### ISSUE TITLE
Cannot find module in production build

### ISSUE THREAD

**Issue by rbluethl** [wannabegeek/ng2-split-pane#39]
Hello,

the module crashes our production build.
Running `ng b --prod` causes the following error:
`Cannot find module '../../../$$_gendir/node_modules/ng2-split-pane/lib/vertical-split-pane.component.ngfactory'`

Versions:

ng2-split-pane: 1.4.0
angular/cli: 1.4.5
angular: 5.0.0-rc.2

Any ideas?

Thanks!
Ronald

**Comment by xileftenurb** [comment]
why was this closed? did you find an answer?
