### ISSUE TITLE
Feature Request: provide handle width as input

### ISSUE THREAD

**Issue by seanspicer** [wannabegeek/ng2-split-pane#5]
Can you expose the handle width as an input?  Currently it is fixed at 7px.   This may not work in all applications.

**Comment by siovene** [comment]
@seanspicer, you can easily override it with your CSS, tho, can't you?

**Comment by siovene** [comment]
@seanspicer actually you are right. Modifying the CSS is not enough because the value of `8px` is hard-coded in `dividerPosition()`.

**Comment by siovene** [comment]
I'm starting working on this.

**Comment by siovene** [comment]
PR#11 submitted.

**Comment by siovene** [comment]
@wannabegeek can you please close this bug? It didn't automatically close via the commit message.

**Comment by siovene** [comment]
@seanspicer this is now implmented in the latest release, if you still need it.
